name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
    paths:
      - Frontend/**
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd Frontend && npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_NAMUROK_7512505 }}"
          channelId: live
          projectId: namurok-7512505
          entryPoint: ./Frontend